#!/usr/bin/env bash

set -e

cd "$(dirname ${0})"

LAST_UPDATED="${LAST_UPDATED:-$(date --iso)}"

docker build \
  --build-arg LAST_UPDATED="${LAST_UPDATED}" \
  --tag "hugojosefson/signal-desktop:latest" \
  .

if [[ "${1}" == "--push" ]]; then
  docker push "hugojosefson/signal-desktop:latest"
fi
